CREATE TABLE providers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(160) NOT NULL,
  legal_name VARCHAR(190) NULL,
  contact_name VARCHAR(120) NULL,
  email VARCHAR(190) NULL,
  phone VARCHAR(40) NULL,
  country VARCHAR(100) NULL,
  service_type VARCHAR(32) NOT NULL DEFAULT 'other',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  notes TEXT NULL,
  created_by_admin_id BIGINT UNSIGNED NULL,
  updated_by_admin_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_providers_name (name),
  KEY idx_providers_status (status),
  KEY idx_providers_service_type (service_type),
  KEY idx_providers_country (country),
  CONSTRAINT fk_providers_created_by_admin FOREIGN KEY (created_by_admin_id) REFERENCES admin_users(id) ON DELETE SET NULL,
  CONSTRAINT fk_providers_updated_by_admin FOREIGN KEY (updated_by_admin_id) REFERENCES admin_users(id) ON DELETE SET NULL,
  CONSTRAINT chk_providers_status CHECK (status IN ('active','inactive')),
  CONSTRAINT chk_providers_service_type CHECK (service_type IN ('tour_operator','transport','lodging','guide','activity','restaurant','other')),
  CONSTRAINT chk_providers_contact CHECK (email IS NOT NULL OR phone IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
