CREATE TABLE fleet (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  plate VARCHAR(40) NOT NULL,
  name VARCHAR(160) NOT NULL,
  vehicle_type VARCHAR(32) NOT NULL DEFAULT 'van',
  brand VARCHAR(80) NULL,
  model VARCHAR(100) NULL,
  model_year SMALLINT UNSIGNED NULL,
  capacity SMALLINT UNSIGNED NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  notes TEXT NULL,
  created_by_admin_id BIGINT UNSIGNED NULL,
  updated_by_admin_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_fleet_plate (plate),
  KEY idx_fleet_status (status),
  KEY idx_fleet_vehicle_type (vehicle_type),
  CONSTRAINT fk_fleet_created_by_admin FOREIGN KEY (created_by_admin_id) REFERENCES admin_users(id) ON DELETE SET NULL,
  CONSTRAINT fk_fleet_updated_by_admin FOREIGN KEY (updated_by_admin_id) REFERENCES admin_users(id) ON DELETE SET NULL,
  CONSTRAINT chk_fleet_status CHECK (status IN ('active','maintenance','inactive')),
  CONSTRAINT chk_fleet_vehicle_type CHECK (vehicle_type IN ('car','suv','van','minibus','bus','boat','other')),
  CONSTRAINT chk_fleet_capacity CHECK (capacity >= 1 AND capacity <= 500),
  CONSTRAINT chk_fleet_year CHECK (model_year IS NULL OR (model_year >= 1950 AND model_year <= 2100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
