INSERT INTO cms_settings (setting_key, setting_value) VALUES
('seo_title', 'Capoy Costa Rica | Tours y experiencias auténticas'),
('seo_description', 'Reservas fáciles, guías locales y experiencias inigualables en los lugares más increíbles del país. Tours, destinos y aventuras inolvidables.'),
('promo_text', 'Rutas 🥾 y tours 🚐 que debes conocer'),
('promo_enabled', 'false'),
('tours_eyebrow', '🍃 TOURS DESTACADOS'),
('tours_title', 'Vive experiencias inolvidables'),
('why_eyebrow', '🍃 ¿POR QUÉ ELEGIR CAPOY COSTA RICA?'),
('why_title', 'Tu aventura, nuestra pasión'),
('destinations_eyebrow', '🍃 DESTINOS POPULARES'),
('destinations_title', 'Descubre lo mejor de Costa Rica'),
('how_eyebrow', '🍃 ¿CÓMO FUNCIONA?'),
('how_title', 'Reservar tu aventura es fácil'),
('testimonials_eyebrow', '🍃 LO QUE DICEN NUESTROS VIAJEROS'),
('testimonials_title', 'Historias reales, experiencias increíbles'),
('faq_eyebrow', 'PREGUNTAS FRECUENTES'),
('faq_title', 'Resolvemos tus dudas'),
('hero_stats', '[{"icon":"Users","value":"15,000+","label":"Viajeros felices","stars":"★★★★★"},{"icon":"Star","value":"4.9/5","label":"Calificación promedio","stars":"★★★★★"},{"icon":"MapPin","value":"50+","label":"Destinos increíbles","stars":""}]'),
('trust_strip', '[{"icon":"ShieldCheck","title":"Operador 100% local","text":"y certificado"},{"icon":"Leaf","title":"Turismo sostenible","text":"y responsable"},{"icon":"Headphones","title":"Soporte 24/7","text":"antes y durante tu viaje"},{"icon":"LockKeyhole","title":"Reservas seguras","text":"y confirmación inmediata"}]'),
('why_items', '[{"icon":"CalendarDays","title":"Reservas fáciles","text":"Reserva en minutos y recibe confirmación inmediata."},{"icon":"Users","title":"Guías locales","text":"Expertos apasionados que conocen cada rincón."},{"icon":"Headphones","title":"Atención personalizada","text":"Te acompañamos antes, durante y después."},{"icon":"Van","title":"Transporte confiable","text":"Unidades cómodas y seguras con aire acondicionado."},{"icon":"Leaf","title":"Experiencias auténticas","text":"Conexión real con la cultura, naturaleza y comunidad."}]'),
('destinations', '[{"name":"Manuel Antonio","subtitle":"Playas, vida silvestre y aventura","image":"https://plus.unsplash.com/premium_photo-1661964589674-21cc0d7e345a?q=80&w=600&auto=format&fit=crop"},{"name":"Arenal","subtitle":"Volcán, aguas termales y bosque tropical","image":"https://images.unsplash.com/photo-1610932748192-06f1ee748b34?q=80&w=600&auto=format&fit=crop"},{"name":"Monteverde","subtitle":"Bosque nuboso y puentes colgantes","image":"https://images.unsplash.com/photo-1580909320993-2569d592e08a?q=80&w=600&auto=format&fit=crop"},{"name":"Guanacaste","subtitle":"Sol, playas doradas y atardeceres","image":"https://images.unsplash.com/photo-1544550285-f813152bbc2a?q=80&w=600&auto=format&fit=crop"},{"name":"Tortuguero","subtitle":"Canales, naturaleza y tortugas marinas","image":"https://images.unsplash.com/photo-1577907549794-494d8d8a6e43?q=80&w=600&auto=format&fit=crop"}]'),
('how_steps', '[{"icon":"MapPin","title":"Elige tu tour","text":"Explora nuestras experiencias y selecciona tu favorita."},{"icon":"CalendarDays","title":"Reserva","text":"Completa tus datos, realiza el pago y recibe confirmación."},{"icon":"Camera","title":"Disfruta","text":"Vive una experiencia increíble y crea recuerdos inolvidables."}]'),
('testimonials', '[{"quote":"La experiencia en La Fortuna fue increíble. Los guías súper profesionales y muy amables. 100% recomendado.","author":"María Fernanda","country":"México"},{"quote":"Todo salió perfecto, desde la reserva hasta el último detalle del tour. Capoy hizo nuestro viaje inolvidable.","author":"Carlos Alberto","country":"Colombia"},{"quote":"El catamarán al atardecer fue mágico. Paisajes hermosos, excelente servicio y mucha diversión.","author":"Laura y Andrés","country":"Argentina"}]'),
('faq_items', '[{"question":"¿Cómo puedo hacer una reserva?","answer":"Nuestro equipo te acompaña en cada paso. Contáctanos para recibir información específica de tu experiencia."},{"question":"¿Puedo reservar un tour en otro idioma?","answer":"Nuestro equipo te acompaña en cada paso. Contáctanos para recibir información específica de tu experiencia."},{"question":"¿Qué incluye el precio del tour?","answer":"Nuestro equipo te acompaña en cada paso. Contáctanos para recibir información específica de tu experiencia."},{"question":"¿Cómo funcionan las reservas grupales?","answer":"Nuestro equipo te acompaña en cada paso. Contáctanos para recibir información específica de tu experiencia."},{"question":"¿Qué pasa si llueve el día de mi tour?","answer":"Nuestro equipo te acompaña en cada paso. Contáctanos para recibir información específica de tu experiencia."},{"question":"¿Debo pagar por adelantado?","answer":"Nuestro equipo te acompaña en cada paso. Contáctanos para recibir información específica de tu experiencia."}]'),
('section_visible', '{"trust":true,"tours":true,"why":true,"destinations":true,"how":true,"testimonials":true,"faq":true,"cta":true}'),
('section_order', '["trust","tours","why","destinations","how","testimonials","faq","cta"]')
ON DUPLICATE KEY UPDATE setting_key = VALUES(setting_key);