const REVIEW_STATUSES=new Set(['pending','published','rejected']);
const REVIEW_SOURCES=new Set(['admin','google','tripadvisor','facebook','website','other']);
function cleanText(value,maxLength){return String(value??'').trim().slice(0,maxLength)}
function nullableText(value,maxLength){const text=cleanText(value,maxLength);return text||null}
function nullableId(value){if(value===null||value===undefined||value==='')return null;const id=Number.parseInt(String(value),10);return Number.isInteger(id)&&id>0?id:NaN}
function reviewPayload(body){
 const customerId=nullableId(body?.customerId),tourId=nullableId(body?.tourId),authorName=cleanText(body?.authorName,120),authorCountry=nullableText(body?.authorCountry,100),rating=Number(body?.rating),title=nullableText(body?.title,180),bodyText=cleanText(body?.body,6000),source=cleanText(body?.source||'admin',32),status=cleanText(body?.status||'pending',32),featured=body?.featured===true;
 if(Number.isNaN(customerId)||Number.isNaN(tourId))return{error:'Cliente o tour inválido.'};
 if(authorName.length<2)return{error:'Autor inválido.'};
 if(!Number.isInteger(rating)||rating<1||rating>5)return{error:'Calificación inválida.'};
 if(bodyText.length<5)return{error:'Comentario demasiado corto.'};
 if(!REVIEW_SOURCES.has(source))return{error:'Fuente inválida.'};
 if(!REVIEW_STATUSES.has(status))return{error:'Estado de reseña inválido.'};
 return{customerId,tourId,authorName,authorCountry,rating,title,body:bodyText,source,status,featured};
}
function mapReview(row){return{id:Number(row.id),customerId:row.customer_id===null?null:Number(row.customer_id),tourId:row.tour_id===null?null:Number(row.tour_id),authorName:row.author_name,authorCountry:row.author_country,rating:Number(row.rating),title:row.title,body:row.body,source:row.source,status:row.status,featured:Boolean(row.featured),customerName:row.customer_name||null,tourName:row.tour_name||null,createdAt:row.created_at,updatedAt:row.updated_at}}
export function registerReviewRoutes({app,pool,requireSession,sameOriginOnly,audit}){
 app.get('/api/admin/reviews',requireSession,async(req,res)=>{try{const status=cleanText(req.query.status,32),rating=cleanText(req.query.rating,8),q=cleanText(req.query.q,120),page=Math.max(1,Number.parseInt(String(req.query.page||'1'),10)||1),limit=Math.min(100,Math.max(10,Number.parseInt(String(req.query.limit||'25'),10)||25)),offset=(page-1)*limit,where=[],params=[];if(status&&status!=='all'){if(!REVIEW_STATUSES.has(status))return res.status(400).json({error:'Filtro de estado inválido.'});where.push('r.status=?');params.push(status)}if(rating&&rating!=='all'){const n=Number(rating);if(!Number.isInteger(n)||n<1||n>5)return res.status(400).json({error:'Filtro de calificación inválido.'});where.push('r.rating=?');params.push(n)}if(q){const like=`%${q}%`;where.push('(r.author_name LIKE ? OR r.author_country LIKE ? OR r.title LIKE ? OR r.body LIKE ? OR t.name LIKE ?)');params.push(like,like,like,like,like)}const clause=where.length?`WHERE ${where.join(' AND ')}`:'';const [[summaryRows],[countRows],[rows]]=await Promise.all([pool.query("SELECT COUNT(*) total,SUM(status='pending') pendingCount,SUM(status='published') publishedCount,SUM(status='rejected') rejectedCount,AVG(rating) averageRating,SUM(featured=1) featuredCount FROM reviews"),pool.execute(`SELECT COUNT(*) total FROM reviews r LEFT JOIN tours t ON t.id=r.tour_id ${clause}`,params),pool.execute(`SELECT r.*,c.full_name customer_name,t.name tour_name FROM reviews r LEFT JOIN customers c ON c.id=r.customer_id LEFT JOIN tours t ON t.id=r.tour_id ${clause} ORDER BY r.created_at DESC LIMIT ? OFFSET ?`,[...params,limit,offset])]);const s=summaryRows[0]||{},total=Number(countRows[0]?.total||0);res.json({ok:true,summary:{total:Number(s.total||0),pending:Number(s.pendingCount||0),published:Number(s.publishedCount||0),rejected:Number(s.rejectedCount||0),averageRating:s.averageRating===null?null:Number(Number(s.averageRating).toFixed(2)),featured:Number(s.featuredCount||0)},pagination:{page,limit,total,pages:Math.max(1,Math.ceil(total/limit))},reviews:rows.map(mapReview)});}catch(error){console.error('reviews_list_failed',error.message);res.status(503).json({error:'No fue posible cargar las reseñas.'})}});
 app.post('/api/admin/reviews',sameOriginOnly,requireSession,async(req,res)=>{const payload=reviewPayload(req.body);if(payload.error)return res.status(400).json({error:payload.error});try{if(payload.customerId){const [rows]=await pool.execute('SELECT id FROM customers WHERE id=? LIMIT 1',[payload.customerId]);if(!rows.length)return res.status(400).json({error:'Cliente inválido.'})}if(payload.tourId){const [rows]=await pool.execute('SELECT id FROM tours WHERE id=? LIMIT 1',[payload.tourId]);if(!rows.length)return res.status(400).json({error:'Tour inválido.'})}const [result]=await pool.execute('INSERT INTO reviews (customer_id,tour_id,author_name,author_country,rating,title,body,source,status,featured,created_by_admin_id,updated_by_admin_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[payload.customerId,payload.tourId,payload.authorName,payload.authorCountry,payload.rating,payload.title,payload.body,payload.source,payload.status,payload.featured?1:0,req.admin.id,req.admin.id]);await audit(req,'review_created',{userId:req.admin.id,email:req.admin.email,metadata:{reviewId:result.insertId,rating:payload.rating,status:payload.status}});res.status(201).json({ok:true,review:{id:Number(result.insertId)}});}catch(error){console.error('review_create_failed',error.message);res.status(503).json({error:'No fue posible crear la reseña.'})}});
 app.patch('/api/admin/reviews/:id',sameOriginOnly,requireSession,async(req,res)=>{const id=Number.parseInt(req.params.id,10);if(!Number.isInteger(id)||id<1)return res.status(400).json({error:'Reseña inválida.'});const payload=reviewPayload(req.body);if(payload.error)return res.status(400).json({error:payload.error});try{if(payload.customerId){const [rows]=await pool.execute('SELECT id FROM customers WHERE id=? LIMIT 1',[payload.customerId]);if(!rows.length)return res.status(400).json({error:'Cliente inválido.'})}if(payload.tourId){const [rows]=await pool.execute('SELECT id FROM tours WHERE id=? LIMIT 1',[payload.tourId]);if(!rows.length)return res.status(400).json({error:'Tour inválido.'})}const [result]=await pool.execute('UPDATE reviews SET customer_id=?,tour_id=?,author_name=?,author_country=?,rating=?,title=?,body=?,source=?,status=?,featured=?,updated_by_admin_id=? WHERE id=?',[payload.customerId,payload.tourId,payload.authorName,payload.authorCountry,payload.rating,payload.title,payload.body,payload.source,payload.status,payload.featured?1:0,req.admin.id,id]);if(!result.affectedRows)return res.status(404).json({error:'Reseña no encontrada.'});await audit(req,'review_updated',{userId:req.admin.id,email:req.admin.email,metadata:{reviewId:id,status:payload.status,featured:payload.featured}});res.json({ok:true});}catch(error){console.error('review_update_failed',error.message);res.status(503).json({error:'No fue posible actualizar la reseña.'})}});
}
