import { useEffect, useMemo, useState } from 'react';

type AuditEvent={id:number;userId:number|null;displayName:string|null;email:string|null;eventType:string;ipAddress:string|null;userAgent:string|null;metadata:Record<string,unknown>|null;createdAt:string};
type AuditResponse={summary:{total:number;last24h:number;actors:number;eventTypes:number};pagination:{page:number;limit:number;total:number;pages:number};eventTypes:{eventType:string;total:number}[];events:AuditEvent[]};

export function AuditPage(){
 const [data,setData]=useState<AuditResponse|null>(null);const [q,setQ]=useState('');const [eventType,setEventType]=useState('all');const [period,setPeriod]=useState('7d');const [page,setPage]=useState(1);const [error,setError]=useState('');
 useEffect(()=>{const params=new URLSearchParams({q,eventType,period,page:String(page),limit:'25'});fetch(`/api/admin/audit?${params}`,{credentials:'same-origin'}).then(async r=>{if(r.status===401){window.location.assign('/admin/login');return null}if(r.status===403){setError('Acceso restringido al propietario.');return null}const body=await r.json();if(!r.ok)throw new Error(body.error||'No fue posible cargar la auditoría.');return body}).then(body=>body&&setData(body)).catch(e=>setError(e.message))},[q,eventType,period,page]);
 const pages=useMemo(()=>data?.pagination.pages||1,[data]);
 return <main className="audit-page"><header className="audit-head"><div><p>CAPOY COSTA RICA</p><h1>Auditoría</h1><span>Historial real de acciones administrativas.</span></div><a href="/admin">← Dashboard</a></header>{error?<div className="audit-error">{error}</div>:<><section className="audit-kpis"><article><b>{data?.summary.total??'—'}</b><span>Eventos totales</span></article><article><b>{data?.summary.last24h??'—'}</b><span>Últimas 24 horas</span></article><article><b>{data?.summary.actors??'—'}</b><span>Actores</span></article><article><b>{data?.summary.eventTypes??'—'}</b><span>Tipos de evento</span></article></section><section className="audit-controls"><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Buscar evento, correo, usuario o IP"/><select value={eventType} onChange={e=>{setEventType(e.target.value);setPage(1)}}><option value="all">Todos los eventos</option>{data?.eventTypes.map(x=><option key={x.eventType} value={x.eventType}>{x.eventType} ({x.total})</option>)}</select><select value={period} onChange={e=>{setPeriod(e.target.value);setPage(1)}}><option value="24h">24 horas</option><option value="7d">7 días</option><option value="30d">30 días</option><option value="90d">90 días</option><option value="all">Todo</option></select></section><section className="audit-table-wrap"><table className="audit-table"><thead><tr><th>Fecha</th><th>Evento</th><th>Usuario</th><th>IP</th><th>Detalles</th></tr></thead><tbody>{data?.events.map(ev=><tr key={ev.id}><td>{new Date(ev.createdAt).toLocaleString('es-CR')}</td><td><strong>{ev.eventType}</strong></td><td>{ev.displayName||ev.email||'Sistema'}</td><td>{ev.ipAddress||'—'}</td><td><code>{ev.metadata?JSON.stringify(ev.metadata):'—'}</code></td></tr>)}</tbody></table>{data?.events.length===0&&<div className="audit-empty">No hay eventos con esos filtros.</div>}</section><footer className="audit-pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page} de {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Siguiente</button></footer></>}</main>
}
