import React from 'react';
import ReactDOM from 'react-dom/client';
import { App } from './App';
import { AdminDashboard } from './AdminDashboard';
import { ReservationsPage } from './ReservationsPage';
import { ToursPage } from './ToursPage';
import { CustomersPage } from './CustomersPage';
import { ProvidersPage } from './ProvidersPage';
import { FleetPage } from './FleetPage';
import { ReviewsPage } from './ReviewsPage';
import { CmsPage } from './CmsPage';
import { UsersPage } from './UsersPage';
import { SettingsPage } from './SettingsPage';
import { CompanySettingsPage } from './CompanySettingsPage';
import { AuditPage } from './AuditPage';
import { PublicCmsBridge } from './PublicCmsBridge';
import { PublicToursBridge } from './PublicToursBridge';
import { PublicCompanyBridge } from './PublicCompanyBridge';
import './styles.css';
import './admin.css';
import './reservations.css';
import './tours.css';
import './customers.css';
import './providers.css';
import './cms.css';
import './users.css';
import './settings.css';
import './audit.css';
import './company.css';
import './login-entry.css';

const pathname = window.location.pathname.replace(/\/$/, '') || '/';
const isReservations = pathname === '/admin/reservas';
const isTours = pathname === '/admin/tours';
const isCustomers = pathname === '/admin/clientes';
const isProviders = pathname === '/admin/proveedores';
const isFleet = pathname === '/admin/flota';
const isReviews = pathname === '/admin/resenas';
const isCms = pathname === '/admin/cms';
const isUsers = pathname === '/admin/usuarios';
const isSettings = pathname === '/admin/configuracion';
const isAudit = pathname === '/admin/auditoria';
const isCompany = pathname === '/admin/empresa';
const isAdminDashboard = pathname === '/admin' || (pathname.startsWith('/admin/') && pathname !== '/admin/login');

const publicScreen = <><App/><PublicCmsBridge/><PublicToursBridge/><PublicCompanyBridge/></>;
const screen = isReservations ? <ReservationsPage/> : isTours ? <ToursPage/> : isCustomers ? <CustomersPage/> : isProviders ? <ProvidersPage/> : isFleet ? <FleetPage/> : isReviews ? <ReviewsPage/> : isCms ? <CmsPage/> : isUsers ? <UsersPage/> : isSettings ? <SettingsPage/> : isAudit ? <AuditPage/> : isCompany ? <CompanySettingsPage/> : isAdminDashboard ? <AdminDashboard/> : publicScreen;
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode>{screen}</React.StrictMode>);
