import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, ClipboardList, Edit3, LayoutDashboard, Loader2, LogOut, Menu, Plus, Search, ShieldCheck, X } from 'lucide-react';

type AdminUser={id:number;displayName:string;email:string;role:string};
type Tour={id:number;slug:string;name:string;destination:string;shortDescription:string|null;description:string|null;duration:string|null;adultPrice:number;childPrice:number|null;currency:string;capacity:number|null;mainImageUrl:string|null;status:string;publishedAt:string|null;createdAt:string;updatedAt:string};
type Payload={summary:{total:number;draft:number;published:number;inactive:number};pagination:{page:number;limit:number;total:number;pages:number};tours:Tour[]};

const statuses=[['draft','Borrador'],['published','Publicado'],['inactive','Inactivo']] as const;
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(v=>v[0]?.toUpperCase()).join('')||'CA'}
function money(value:number,currency:string){return new Intl.NumberFormat('es-CR',{style:'currency',currency}).format(value)}

export function ToursPage(){
  const [user,setUser]=useState<AdminUser|null>(null);const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const [modal,setModal]=useState(false);const [editing,setEditing]=useState<Tour|null>(null);const [saving,setSaving]=useState(false);const [saveError,setSaveError]=useState('');const [mobileMenu,setMobileMenu]=useState(false);

  async function load(){setLoading(true);setError('');try{const params=new URLSearchParams({page:'1',limit:'100'});if(status!=='all')params.set('status',status);if(query.trim())params.set('q',query.trim());const [s,t]=await Promise.all([fetch('/api/auth/session',{credentials:'same-origin'}),fetch(`/api/admin/tours?${params}`,{credentials:'same-origin'})]);if(s.status===401||t.status===401){window.location.assign('/admin/login');return}if(!s.ok||!t.ok){const b=await t.json().catch(()=>({}));throw new Error(b.error||'No fue posible cargar los tours.')}setUser((await s.json()).user);setData(await t.json())}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar los tours.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function logout(){await fetch('/api/auth/logout',{method:'POST',credentials:'same-origin'}).catch(()=>null);window.location.assign('/admin/login')}
  function openCreate(){setEditing(null);setSaveError('');setModal(true)}
  function openEdit(tour:Tour){setEditing(tour);setSaveError('');setModal(true)}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setSaveError('');const form=new FormData(event.currentTarget);const payload={name:String(form.get('name')||''),slug:String(form.get('slug')||''),destination:String(form.get('destination')||''),shortDescription:String(form.get('shortDescription')||''),description:String(form.get('description')||''),duration:String(form.get('duration')||''),adultPrice:String(form.get('adultPrice')||'0'),childPrice:String(form.get('childPrice')||''),currency:String(form.get('currency')||'USD'),capacity:String(form.get('capacity')||''),mainImageUrl:String(form.get('mainImageUrl')||''),status:String(form.get('status')||'draft')};try{const response=await fetch(editing?`/api/admin/tours/${editing.id}`:'/api/admin/tours',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(payload)});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'No fue posible guardar el tour.');setModal(false);setEditing(null);await load()}catch(e){setSaveError(e instanceof Error?e.message:'No fue posible guardar el tour.')}finally{setSaving(false)}}

  return <div className="tours-app"><aside className={`tours-sidebar ${mobileMenu?'open':''}`}><div className="tours-brand"><span>C</span><div><strong>Capoy</strong><small>Costa Rica</small></div><button onClick={()=>setMobileMenu(false)}><X size={20}/></button></div><nav><a href="/admin"><LayoutDashboard size={18}/> Dashboard</a><a href="/admin/reservas"><ClipboardList size={18}/> Reservas</a><a className="active" href="/admin/tours"><ClipboardList size={18}/> Tours</a></nav><div className="tours-sidebar-bottom"><div><ShieldCheck size={16}/> Sesión protegida</div>{user&&<div className="tours-user"><span>{initials(user.displayName)}</span><div><strong>{user.displayName}</strong><small>{user.role}</small></div></div>}<button onClick={logout}><LogOut size={17}/> Cerrar sesión</button></div></aside>{mobileMenu&&<button className="tours-backdrop" onClick={()=>setMobileMenu(false)}/>}
  <main className="tours-main"><header className="tours-topbar"><div><button onClick={()=>setMobileMenu(true)}><Menu size={20}/></button><a href="/admin"><ArrowLeft size={17}/> Administración</a><span>/</span><strong>Tours</strong></div></header><section className="tours-content"><div className="tours-heading"><div><span>CATÁLOGO OPERATIVO</span><h1>Tours</h1><p>Crea, publica y administra las experiencias que vende Capoy.</p></div><button onClick={openCreate}><Plus size={18}/> Nuevo tour</button></div>
  {data&&<div className="tours-kpis"><article><span>Total</span><strong>{data.summary.total}</strong><small>Experiencias</small></article><article><span>Publicados</span><strong>{data.summary.published}</strong><small>Visibles para operación</small></article><article><span>Borradores</span><strong>{data.summary.draft}</strong><small>En preparación</small></article><article><span>Inactivos</span><strong>{data.summary.inactive}</strong><small>Fuera de venta</small></article></div>}
  <div className="tours-toolbar"><form onSubmit={e=>{e.preventDefault();load()}}><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nombre, destino o slug"/><button>Buscar</button></form><select value={status} onChange={e=>{setStatus(e.target.value);setTimeout(load,0)}}><option value="all">Todos los estados</option>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
  {loading&&<div className="tours-state"><Loader2 className="spin"/> Cargando tours…</div>}{!loading&&error&&<div className="tours-state error">{error}</div>}{!loading&&!error&&data?.tours.length===0&&<div className="tours-empty"><ClipboardList size={36}/><h2>No hay tours todavía</h2><p>El catálogo está listo y conectado a MySQL.</p><button onClick={openCreate}><Plus size={17}/> Crear primer tour</button></div>}
  {!loading&&!error&&data&&data.tours.length>0&&<div className="tours-grid">{data.tours.map(t=><article key={t.id}>{t.mainImageUrl?<img src={t.mainImageUrl} alt={t.name}/>:<div className="tour-placeholder">Sin imagen</div>}<div className="tour-card-body"><div className="tour-card-top"><span className={`tour-status ${t.status}`}>{statuses.find(s=>s[0]===t.status)?.[1]||t.status}</span><button onClick={()=>openEdit(t)}><Edit3 size={16}/> Editar</button></div><h2>{t.name}</h2><p>{t.destination}{t.duration?` · ${t.duration}`:''}</p><small>{t.shortDescription||'Sin descripción corta'}</small><div className="tour-prices"><strong>{money(t.adultPrice,t.currency)}</strong><span>Adulto</span>{t.childPrice!==null&&<><strong>{money(t.childPrice,t.currency)}</strong><span>Niño</span></>}</div><code>/{t.slug}</code></div></article>)}</div>}</section></main>
  {modal&&<div className="tour-modal"><button className="tour-modal-backdrop" onClick={()=>setModal(false)}/><section><header><div><span>{editing?'EDITAR TOUR':'NUEVO TOUR'}</span><h2>{editing?editing.name:'Crear experiencia'}</h2></div><button onClick={()=>setModal(false)}><X size={20}/></button></header><form onSubmit={save}><div className="tour-form-grid"><label>Nombre<input name="name" defaultValue={editing?.name||''} maxLength={180} required/></label><label>Slug<input name="slug" defaultValue={editing?.slug||''} placeholder="se genera desde el nombre" maxLength={190}/></label><label>Destino<input name="destination" defaultValue={editing?.destination||''} maxLength={160} required/></label><label>Duración<input name="duration" defaultValue={editing?.duration||''} maxLength={80} placeholder="8 horas"/></label><label>Precio adulto<input name="adultPrice" type="number" min="0" step="0.01" defaultValue={editing?.adultPrice??0} required/></label><label>Precio niño<input name="childPrice" type="number" min="0" step="0.01" defaultValue={editing?.childPrice??''}/></label><label>Moneda<input name="currency" defaultValue={editing?.currency||'USD'} maxLength={3} required/></label><label>Capacidad<input name="capacity" type="number" min="1" defaultValue={editing?.capacity??''}/></label><label className="wide">Imagen principal URL<input name="mainImageUrl" type="url" defaultValue={editing?.mainImageUrl||''}/></label><label>Estado<select name="status" defaultValue={editing?.status||'draft'}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="wide">Descripción corta<input name="shortDescription" defaultValue={editing?.shortDescription||''} maxLength={320}/></label><label className="wide">Descripción<textarea name="description" rows={5} defaultValue={editing?.description||''}/></label></div>{saveError&&<div className="tour-form-error">{saveError}</div>}<footer><button type="button" onClick={()=>setModal(false)}>Cancelar</button><button className="primary" disabled={saving}>{saving?<><Loader2 className="spin" size={17}/> Guardando…</>:(editing?'Guardar cambios':'Crear tour')}</button></footer></form></section></div>}</div>
}
